{{- if .Values.global.defaultPodDisruptionBudget.enabled }}
{{- range $name, $options:= .Values.deployments }}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}
  namespace: {{ $options.namespace | default $.Release.Namespace }}
  labels:
{{ .labels | toYaml | trim | indent 4 }}
    release: {{ $.Release.Name }}
    istio.io/rev: {{ $.Values.revision | default "default" }}
    install.operator.istio.io/owning-resource: {{ $.Values.ownerName | default "unknown" }}
    operator.istio.io/component: "IngressGateways"
spec:
  minAvailable: 1
  selector:
    matchLabels:
{{ .labels | toYaml | trim | indent 6 }}
{{- end }}
{{- end }}
